Repository transferwise/icons, pull requests merged in 2022-08, with the labels that each got.

#150 Change size prop back to string to not break ng-switch
  CHANGELOG.md
  package.json
  src/build-scripts/utils/index.ts
Labels: bug

#157 Change default icon size in v3 to be 16px again
  CHANGELOG.md
  package.json
  src/build-scripts/utils/react-components.ts
Labels: bug, change:standard

#158 Ds 2573 icons console warning
  CHANGELOG.md
  README.md
  package.json
  src/build-scripts/utils/react-components.ts
Labels: bug, enhancement

#177 Was spamming everyone with the console warning about filled variant
  CHANGELOG.md
  package.json
  src/build-scripts/build-icon-components.ts
  src/build-scripts/utils/react-components.ts
Labels: bug
